### ISSUE TITLE
Detection works but the virtual content (coordinate system and ray) offset with some transformation

### ISSUE THREAD

**Issue by qian256** [microsoft/HoloLens2ForCV#1]
Awesome!
When I run the CameraWithCVAndCalibration sample, I can see the two coordinate systems and two rays showing the direction of marker from the coordinate systems of the two VLC cameras. Is it an issue or a feature that the rays do not align with the actual physical device? It looks like the origin of the whole virtual scene is offseted with a transformation.

**Comment by dorinung** [comment]
Thank you for your feedback. This is by design. The app shows a "birds eye view" of the ray triangulation. I am working on additions to the app that will render in the device coordinate system.

**Comment by qian256** [comment]
Thank you. The additional feature to superimpose on the physical world (device coordinate system) would be very helpful.
