### ISSUE TITLE
 How to rectify depth images from ATAH/Long Throw camera sensors of HoloLens2?

### ISSUE THREAD

**Issue by soberkiki** [microsoft/HoloLens2ForCV#108]
Hello.When I reconstructed the point cloud via the sensor of the depth camera, the point cloud was inaccurate due to the distortion of the camera.Does anyone have any methods or suggestions on how to rectify images taken by depth cameras.The images below are point cloud views from three perspectives.
![7dbd4ccdbc4ca39fa1265716ca58634](https://user-images.githubusercontent.com/67571209/141673895-0a4cd4bb-29c4-462a-9e54-6a34004f6aab.png)

![dffc977f404cd1fad6cef09fb3e0bb7](https://user-images.githubusercontent.com/67571209/141673900-77b99e30-f264-40bd-9c8a-6d80df106050.png)
![5cd7f303f6c405597315b70b3bc5b9c](https://user-images.githubusercontent.com/67571209/141673901-015bcb44-2102-49a8-b319-d7f02623b8a0.png)

**Comment by agroenenberg** [comment]
@soberkiki I seem to be having the same problem when reconstruction without the lookuptable, did you find a solution?

**Comment by felixvh** [comment]
The lookup table is supposed to be used for this reason. Why do you want to reconstruct it without the LUT?

**Comment by agroenenberg** [comment]
I need to do some recalculations for my research, but I found it! Simple mistake, thanks!
