### ISSUE TITLE
Excuse me, left_ Left and left_ Front what's the difference between the two cameras

### ISSUE THREAD

**Issue by shoukailiang** [microsoft/HoloLens2ForCV#124]
Excuse me, left_ Left and left_ Front what's the difference between the two cameras

**Comment by felixvh** [comment]
As shown here https://github.com/microsoft/HoloLens2ForCV/blob/main/Docs/ResearchMode-ApiDoc.pdf on page 7, those are the two visible light cameras on the left.

**Comment by shoukailiang** [comment]
oh,thanks.
