### ISSUE TITLE
Notation mistake of coordinate frame in api document

### ISSUE THREAD

**Issue by petergu684** [microsoft/HoloLens2ForCV#13]
I was trying to understand the extrinsic between different cameras based on the Figure 1 in api document (page 7, https://github.com/microsoft/HoloLens2ForCV/blob/main/Docs/ResearchMode-ApiDoc.pdf) and noticed a mistake in y-axis of AHAT/Long throw camera. I assume the y-axis should be into the plane (cross) to make it right-handed.

**Comment by dorinung** [comment]
Thanks for pointing this out. I have corrected the diagram.
