### ISSUE TITLE
CameraWithCVAndCalibration runtime error: Unable to activate Microsoft Store app

### ISSUE THREAD

**Issue by nothingbut1** [microsoft/HoloLens2ForCV#153]
Hello and thanks for these useful samples. 

**I am able to run all the samples except "CameraWithCVAndCalibration"**. 

Here is my procedure:
1. Open the CameraWithCVAndCalibration.sln file in Visual Studio, build (Debug, ARM64), errors occured：
![屏幕截图 2022-12-07 113455](https://user-images.githubusercontent.com/20449826/206153394-d7520038-da38-4a39-b267-9a3e0b333be9.png)
so I check the property settings, and add the opencv_world412d.lib path to the Library Directories:
![屏幕截图 2022-12-07 113154](https://user-images.githubusercontent.com/20449826/206153816-523021e7-7c93-4344-99b0-0c741cef23ed.png)
rebuild, succedded with two warnings (these warning matters ?):
![屏幕截图 2022-12-07 114500](https://user-images.githubusercontent.com/20449826/206154248-69f5d32e-e93c-4344-990d-c37eeca6c692.png)

2. Deploy succeeded.
![image](https://user-images.githubusercontent.com/20449826/206155654-e6b3aef5-0a8e-4d41-b51e-aa02fcb53aff.png)

3.  Press F5 to debug, an error window displayed as follows:
![屏幕截图 2022-12-07 114833](https://user-images.githubusercontent.com/20449826/206150700-136b568d-4050-4256-ade8-20f08d34f2d8.png)
press OK, another error window displayed as follows:
![屏幕截图 2022-12-07 114856](https://user-images.githubusercontent.com/20449826/206156944-a81c4757-65d8-468a-8da6-ee4dced9d5d9.png)
 and in the visual studio output window shows:
![屏幕截图 2022-12-07 114937](https://user-images.githubusercontent.com/20449826/206150869-c2aa02a6-bffc-4804-82d6-5bce6803bf3b.png)
**It seems that there are some errors with dll library**, but I don't know how to fix it.

 I have refered to the issues #8 and #41 with similar error, but it doen't works for me. 
 Device Portal and Research Mode are all enabled.
 ![屏幕截图 2022-12-07 101227](https://user-images.githubusercontent.com/20449826/206158165-331f684c-9222-4444-88c2-c728da83c8e7.png)

Environment：
Hololens: beta developer mode, Windows version 22621.1036.arm64fre.ni_release_svc_sydney.221129-1357
visual studio 2022 professional

Any help would be grately appreciated!

**Comment by joriswa** [comment]
The opencv lib is stored with Git LFS so you need clone it with Git LFS. Otherwise the file will be empty

**Comment by nothingbut1** [comment]
@joriswa 
> The opencv lib is stored with Git LFS so you need clone it with Git LFS. Otherwise the file will be empty

Thanks for your reply. I had noticed this, so the repository is cloned with Git LFS. 
![屏幕截图 2022-12-08 093220](https://user-images.githubusercontent.com/20449826/206335093-45dbd7c5-ccf7-48a1-afd6-2bbb5a9ac80d.png)

The cloned opencv_world412d.lib is only about 1.9 Mb, is it normal ?
![屏幕截图 2022-12-08 094402](https://user-images.githubusercontent.com/20449826/206335363-19e028ee-8ee6-4341-9ee1-08cab56e4cc7.png)
![image](https://user-images.githubusercontent.com/20449826/206336466-dec78b67-41b8-4997-a4bf-3fd59ea5c8df.png)

**Comment by nothingbut1** [comment]
see #96
