### ISSUE TITLE
Recording mode in Hololens 2

### ISSUE THREAD

**Issue by rahidraghav** [microsoft/HoloLens2ForCV#16]
I have been trying to activate the research mode and run the samples, However the windows developer portal only displays Recording mode and the applications fail on deployments with "Access Denied" . Can you help what the issue is?

**Comment by kysucix** [comment]
you need a recent build, see [here](https://github.com/microsoft/HoloLens2ForCV/issues/8#issuecomment-685043035)

**Comment by dorinung** [comment]
Also please activate Research mode in the device portal.
