### ISSUE TITLE
StreamRecorderApp is not working

### ISSUE THREAD

**Issue by Birkenpapier** [microsoft/HoloLens2ForCV#17]
Hello everybody,

I just wanted to experiment a little bit with the new functionalities but sadly none of them (except CalibrationVisualization) is working currently.
It would be nice if at least the StreamRecorderApp would work.
The Error is:

![92891158-03e5b680-f418-11ea-9744-daf380e8217e](https://user-images.githubusercontent.com/11006393/93049789-06d3e780-f662-11ea-80c9-f18daf5a7357.png)

What can I do to solve this issue?
Everything is so far set up.
System build (HL): 10.0.19041.1375
Windows Insider Preview is set on.
Research Mode is enabled.

Thank you very much in advance.

**Comment by dorinung** [comment]
You might be running into this: https://github.com/microsoft/HoloLens2ForCV/issues/11. Please make sure the samples are built using ARM64 rather than ARM.
