### ISSUE TITLE
Occur Crush in InitializeSensors()

### ISSUE THREAD

**Issue by forarete** [microsoft/HoloLens2ForCV#24]
Hello,

I'm newbee on hololense developer, and thanks your contributions.

I have troubled to run sample projects.

The sample 'CalibrationVisualization' is OK. But the others are not worked.

When I tried debugging, the error occurred on line below.

 winrt::check_hresult(m_pSensorDevice->QueryInterface(IID_PPV_ARGS(&m_pSensorDeviceConsent)));

![image](https://user-images.githubusercontent.com/8287073/93751895-cb748280-fc38-11ea-86cd-84a03f77a4c2.png)

In here, 'check_hresult' throws the exception 
![image](https://user-images.githubusercontent.com/8287073/93752033-07a7e300-fc39-11ea-9c15-300b380a10de.png)

Of course, I already allowed access to camera stream in [hololense2 setting/privacy] and [device portal/research mode].

Please let me know the solution. 
Thanks!

**Comment by dorinung** [comment]
What version of the OS do you have on Hololens? Thanks.

**Comment by forarete** [comment]
It's

Windows version	19041.1117.arm64fre.vb_release_svc_sydney_rel_prod.200903-1632


Thanks.

**Comment by dorinung** [comment]
The earliest build that fully supports research mode is 19041.1364. Please join the Windows Insider Program to get preview builds. After that, in the device portal, enable research mode, different than recording mode. See https://github.com/microsoft/HoloLens2ForCV/blob/main/Docs/ECCV2020-Tutorial/ECCV2020-ResearchMode-Api.pdf (slides 6, 7 and 8) or Setup section in https://github.com/microsoft/HoloLens2ForCV/blob/main/Docs/ResearchMode-ApiDoc.pdf.

**Comment by forarete** [comment]
It works after updating preview build!

I thought my OS was up to date because I updated it in settings. But it was not preview build version you mentioned.

Sorry for confusing you.

Thanks!
