### ISSUE TITLE
CameraWithCVAndCalibration Project release issues

### ISSUE THREAD

**Issue by RenSiyao** [microsoft/HoloLens2ForCV#26]
Samples \ CameraWithCVAndCalibration \ OpenCvInstallArm64-412 - d contains arm64 headers and Opencv library distribution.These require Git LFS. What does that mean。
I didn't follow the above method because I didn't know what to do, so I posted the following error，Can someone help me out
![image](https://user-images.githubusercontent.com/53859046/93956780-827e1480-fd85-11ea-84a8-81aef0e7c4c5.png)

**Comment by dorinung** [comment]
Please see https://git-lfs.github.com/. Thanks.

**Comment by RenSiyao** [comment]
Thank you for your reply. May I ask you more questions by email?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dorin Ungureanu"<notifications@github.com&gt;; 
发送时间: 2020年9月23日(星期三) 上午10:18
收件人: "microsoft/HoloLens2ForCV"<HoloLens2ForCV@noreply.github.com&gt;; 
抄送: "Albert。Siyao"<962675641@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [microsoft/HoloLens2ForCV] CameraWithCVAndCalibration Project release issues (#26)





 
Closed #26.
