### ISSUE TITLE
Question about framerates of different cameras

### ISSUE THREAD

**Issue by aal-rvr** [microsoft/HoloLens2ForCV#42]
Hi,

I did some experiments with the `DEPTH_AHAT` framerate. For all my tests, I ran `SensorVisualization` sample with some frame processing using OpenCV. The application was in the `Release` configuration and only the `DEPTH_AHAT` sensor running.
With all the extra processing the frame rate dropped and I got a framerate of `16 to 45 fps`, with an average of `18 fps` over `10000 frames`.
I noticed that when the Hololens is lying still (on a table or a stand) OR the image in front of the Hololens doesn't move, the framerate drops to a constant framerate of `5 fps`. Any changes in the frame causes the framerate to immediately jump up to the aforementioned average of `18fps (ranging from 16fps to 45 fps)`. This suggests some sort of adaptive framerate.

Am I understanding this correctly, does some sort of filtering take place to change the framerate?
If so, does this also happen for other sensors (I have only tested `DEPTH_AHAT`)?
Is there any way to stop this from happening?

Thanks.

**Comment by dorinung** [comment]
The research mode API shares access to the AHAT camera with  the hand tracker. The hand tracker controls the AHAT frame rate and with the API as it works today it is not possible to change the behavior you are observing. We will consider changing this behavior in future versions.
