### ISSUE TITLE
Updating the building to support research mode

### ISSUE THREAD

**Issue by guillermoacdc** [microsoft/HoloLens2ForCV#70]
Well, i have this build on my device
Windows version19041.**1113.**arm64fre.vb_release_svc_sydney_rel_prod.200808-1020
And the requirements on the tutorial indicate
The earliest build that fully supports research mode is 19041.**1364**

So, I guess that it is necessary to update the windows version on my Hololens2. The alternative to resolve this update is the Windows insider Program. There, I have three options  (Dev, Beta and Release). I have selected the Beta channel and after a restart I have used the windows update. I was expecting to obtain the 19041.1364 version but the update was made for version 19041.**1134**.arm64fre.vb_release_svc_sydney_rel_prod.210111-1541

I suppose that this can be a consequence of 

1. Selection of incorrect channel. So I will change to Dev Channel
2. Language on the OS of my device (currently is spanish). So I will change to english language

Before doing so I would like to have your opinion on this guys

Thanks in advance

**Comment by JiangTao100** [comment]
my version is 19041.1136,  but it shows the latest  one and cannot be updated anymore.

**Comment by guillermoacdc** [comment]
"Research-Mode". See attached image

**My interpretation**: The OS of my device is not updated, so the "research-mode" option is missing

Currently my device has buildings of 19041.1113..., and the tutorial indicates that "earliest build that fully supports research mode is 19041.1364"

**What I have done**:  update the OS version using Windows insider Program / Beta Channel.

After this I have advanced to building 19041.1134..., not enough to the reference in the tutorial. The "Research-Mode" is still missing in my device portal

**My real question**: How can I update my OS to building 19041.1364 or later

**My current OS version**: 19041.1134, Spanish language


![Query1_ResearchMode](https://user-images.githubusercontent.com/36015643/107789952-39bcfd00-6d20-11eb-986f-195cc7dd115f.png)

**Comment by guillermoacdc** [comment]
Hello guys

I have updated my language settings to English and now the "Research Mode" is available in the Device-Portal. Thks!
Build

19041.1134.arm64fre.vb_release_svc_sydney_rel_prod.210111-1541
![Query1_solved_ResearchMode](https://user-images.githubusercontent.com/36015643/107889632-05913a00-6ee2-11eb-8890-4454885c3090.png)
